// This file is automatically generated by a script based on the CommandBuilder API.
// It stands in for CommandBuilder.cs and CommandBuilder2D.cs when ALINE is excluded from
// standalone builds. Every method keeps its signature and does nothing.
#if ALINE_EXCLUDED_IN_BUILD && !UNITY_EDITOR
using System;
using UnityEngine;
using System.Collections.Generic;
using Unity.Collections;
using Unity.Mathematics;
using Unity.Jobs;

namespace Pathfinding.Drawing {
	public partial struct CommandBuilder : IDisposable {
		/// <summary>\copydocref{CommandBuilder.xy}</summary>
		public CommandBuilder2D xy => new CommandBuilder2D(this, true);

		/// <summary>\copydocref{CommandBuilder.xz}</summary>
		public CommandBuilder2D xz => new CommandBuilder2D(this, false);

		/// <summary>Always null, because nothing is rendered when ALINE is excluded from builds</summary>
		public Camera[] cameraTargets { get => null; set {} }


		public void Dispose () {
		}

		public void DisposeAfter (JobHandle dependency, AllowedDelay allowedDelay = AllowedDelay.EndOfFrame) {
		}

		public void DiscardAndDispose () {
		}

		public void Preallocate (int size) {
		}

		public ScopeMatrix WithMatrix (Matrix4x4 matrix) {
			return default;
		}

		public ScopeMatrix WithMatrix (float3x3 matrix) {
			return default;
		}

		public ScopeColor WithColor (Color color) {
			return default;
		}

		public ScopePersist WithDuration (float duration) {
			return default;
		}

		public ScopeLineWidth WithLineWidth (float pixels, bool automaticJoins = true) {
			return default;
		}

		public ScopeMatrix InLocalSpace (Transform transform) {
			return default;
		}

		public ScopeMatrix InScreenSpace (Camera camera) {
			return default;
		}

		public void PushMatrix (Matrix4x4 matrix) {
		}

		public void PushMatrix (float4x4 matrix) {
		}

		public void PushSetMatrix (Matrix4x4 matrix) {
		}

		public void PushSetMatrix (float4x4 matrix) {
		}

		public void PopMatrix () {
		}

		public void PushColor (Color color) {
		}

		public void PopColor () {
		}

		public void PushDuration (float duration) {
		}

		public void PopDuration () {
		}

		public void PushPersist (float duration) {
		}

		public void PopPersist () {
		}

		public void PushLineWidth (float pixels, bool automaticJoins = true) {
		}

		public void PopLineWidth () {
		}

		public void Line (float3 a, float3 b) {
		}

		public void Line (Vector3 a, Vector3 b) {
		}

		public void Line (Vector3 a, Vector3 b, Color color) {
		}

		public void Ray (float3 origin, float3 direction) {
		}

		public void Ray (Ray ray, float length) {
		}

		public void Arc (float3 center, float3 start, float3 end) {
		}

		public void CircleXZ (float3 center, float radius, float startAngle = 0f, float endAngle = 2 * Mathf.PI) {
		}

		public void CircleXY (float3 center, float radius, float startAngle = 0f, float endAngle = 2 * Mathf.PI) {
		}

		public void Circle (float3 center, float3 normal, float radius) {
		}

		public void SolidArc (float3 center, float3 start, float3 end) {
		}

		public void SolidCircleXZ (float3 center, float radius, float startAngle = 0f, float endAngle = 2 * Mathf.PI) {
		}

		public void SolidCircleXY (float3 center, float radius, float startAngle = 0f, float endAngle = 2 * Mathf.PI) {
		}

		public void SolidCircle (float3 center, float3 normal, float radius) {
		}

		public void SphereOutline (float3 center, float radius) {
		}

		public void WireCylinder (float3 bottom, float3 top, float radius) {
		}

		public void WireCylinder (float3 position, float3 up, float height, float radius) {
		}

		public void WireCapsule (float3 start, float3 end, float radius) {
		}

		public void WireCapsule (float3 position, float3 direction, float length, float radius) {
		}

		public void WireSphere (float3 position, float radius) {
		}

		public void Polyline (List<Vector3> points, bool cycle = false) {
		}

		public void Polyline (Vector3[] points, bool cycle = false) {
		}

		public void Polyline (float3[] points, bool cycle = false) {
		}

		public void Polyline (NativeArray<float3> points, bool cycle = false) {
		}

		public void DashedLine (float3 a, float3 b, float dash, float gap) {
		}

		public void DashedPolyline (List<Vector3> points, float dash, float gap) {
		}

		public void WireBox (float3 center, float3 size) {
		}

		public void WireBox (float3 center, quaternion rotation, float3 size) {
		}

		public void WireBox (Bounds bounds) {
		}

		public void WireMesh (Mesh mesh) {
		}

		public void WireMesh (NativeArray<float3> vertices, NativeArray<int> triangles) {
		}

		public void SolidMesh (Mesh mesh) {
		}

		public void SolidMesh (List<Vector3> vertices, List<int> triangles, List<Color> colors) {
		}

		public void SolidMesh (Vector3[] vertices, int[] triangles, Color[] colors, int vertexCount, int indexCount) {
		}

		public void Cross (float3 position, float size = 1) {
		}

		public void CrossXZ (float3 position, float size = 1) {
		}

		public void CrossXY (float3 position, float size = 1) {
		}

		public void Bezier (float3 p0, float3 p1, float3 p2, float3 p3) {
		}

		public void CatmullRom (List<Vector3> points) {
		}

		public void CatmullRom (float3 p0, float3 p1, float3 p2, float3 p3) {
		}

		public void Arrow (float3 from, float3 to) {
		}

		public void Arrow (float3 from, float3 to, float3 up, float headSize) {
		}

		public void ArrowRelativeSizeHead (float3 from, float3 to, float3 up, float headFraction) {
		}

		public void Arrowhead (float3 center, float3 direction, float radius) {
		}

		public void Arrowhead (float3 center, float3 direction, float3 up, float radius) {
		}

		public void ArrowheadArc (float3 origin, float3 direction, float offset, float width = 60) {
		}

		public void WireGrid (float3 center, quaternion rotation, int2 cells, float2 totalSize) {
		}

		public void WireTriangle (float3 a, float3 b, float3 c) {
		}

		public void WireRectangleXZ (float3 center, float2 size) {
		}

		public void WireRectangle (float3 center, quaternion rotation, float2 size) {
		}

		public void WireRectangle (Rect rect) {
		}

		public void WireTriangle (float3 center, quaternion rotation, float radius) {
		}

		public void WirePentagon (float3 center, quaternion rotation, float radius) {
		}

		public void WireHexagon (float3 center, quaternion rotation, float radius) {
		}

		public void WirePolygon (float3 center, int vertices, quaternion rotation, float radius) {
		}

		public void SolidRectangle (Rect rect) {
		}

		public void SolidPlane (float3 center, float3 normal, float2 size) {
		}

		public void SolidPlane (float3 center, quaternion rotation, float2 size) {
		}

		public void WirePlane (float3 center, float3 normal, float2 size) {
		}

		public void WirePlane (float3 center, quaternion rotation, float2 size) {
		}

		public void PlaneWithNormal (float3 center, float3 normal, float2 size) {
		}

		public void PlaneWithNormal (float3 center, quaternion rotation, float2 size) {
		}

		public void SolidTriangle (float3 a, float3 b, float3 c) {
		}

		public void SolidBox (float3 center, float3 size) {
		}

		public void SolidBox (Bounds bounds) {
		}

		public void SolidBox (float3 center, quaternion rotation, float3 size) {
		}

		public void WireRing (float3 center, float3 normal, float innerRadius, float outerRadius) {
		}

		public void SolidRing (float3 center, float3 normal, float innerRadius, float outerRadius) {
		}

		public void WireRing (float3 center, quaternion rotation, float innerRadius, float outerRadius, float startAngle = 0f, float endAngle = 2 * Mathf.PI) {
		}

		public void SolidRing (float3 center, quaternion rotation, float innerRadius, float outerRadius, float startAngle = 0f, float endAngle = 2 * Mathf.PI) {
		}

		public void Label3D (float3 position, quaternion rotation, string text, float size) {
		}

		public void Label3D (float3 position, quaternion rotation, string text, float size, LabelAlignment alignment) {
		}

		public void Label2D (float3 position, string text, float sizeInPixels = 14) {
		}

		public void Label2D (float3 position, string text, float sizeInPixels, LabelAlignment alignment) {
		}

		public void Label2D (float3 position, ref FixedString32Bytes text, float sizeInPixels = 14) {
		}

		public void Label2D (float3 position, ref FixedString64Bytes text, float sizeInPixels = 14) {
		}

		public void Label2D (float3 position, ref FixedString128Bytes text, float sizeInPixels = 14) {
		}

		public void Label2D (float3 position, ref FixedString512Bytes text, float sizeInPixels = 14) {
		}

		public void Label2D (float3 position, ref FixedString32Bytes text, float sizeInPixels, LabelAlignment alignment) {
		}

		public void Label2D (float3 position, ref FixedString64Bytes text, float sizeInPixels, LabelAlignment alignment) {
		}

		public void Label2D (float3 position, ref FixedString128Bytes text, float sizeInPixels, LabelAlignment alignment) {
		}

		public void Label2D (float3 position, ref FixedString512Bytes text, float sizeInPixels, LabelAlignment alignment) {
		}

		public void Label3D (float3 position, quaternion rotation, ref FixedString32Bytes text, float size) {
		}

		public void Label3D (float3 position, quaternion rotation, ref FixedString64Bytes text, float size) {
		}

		public void Label3D (float3 position, quaternion rotation, ref FixedString128Bytes text, float size) {
		}

		public void Label3D (float3 position, quaternion rotation, ref FixedString512Bytes text, float size) {
		}

		public void Label3D (float3 position, quaternion rotation, ref FixedString32Bytes text, float size, LabelAlignment alignment) {
		}

		public void Label3D (float3 position, quaternion rotation, ref FixedString64Bytes text, float size, LabelAlignment alignment) {
		}

		public void Label3D (float3 position, quaternion rotation, ref FixedString128Bytes text, float size, LabelAlignment alignment) {
		}

		public void Label3D (float3 position, quaternion rotation, ref FixedString512Bytes text, float size, LabelAlignment alignment) {
		}
		public void Polyline<T>(T points, bool cycle = false) where T : IReadOnlyList<float3> {
		}
	}

	public partial struct CommandBuilder2D {
		public CommandBuilder2D(CommandBuilder draw, bool xy) {}


		public void Line (float2 a, float2 b) {
		}

		public void Line (float2 a, float2 b, Color color) {
		}

		public void Line (float3 a, float3 b) {
		}

		public void Circle (float2 center, float radius, float startAngle = 0f, float endAngle = 2 * math.PI) {
		}

		public void Circle (float3 center, float radius, float startAngle = 0f, float endAngle = 2 * math.PI) {
		}

		public void SolidCircle (float2 center, float radius, float startAngle = 0f, float endAngle = 2 * math.PI) {
		}

		public void SolidCircle (float3 center, float radius, float startAngle = 0f, float endAngle = 2 * math.PI) {
		}

		public void WirePill (float2 a, float2 b, float radius) {
		}

		public void WirePill (float2 position, float2 direction, float length, float radius) {
		}

		public void Polyline (List<Vector2> points, bool cycle = false) {
		}

		public void Polyline (Vector2[] points, bool cycle = false) {
		}

		public void Polyline (float2[] points, bool cycle = false) {
		}

		public void Polyline (NativeArray<float2> points, bool cycle = false) {
		}

		public void Cross (float2 position, float size = 1) {
		}

		public void WireRectangle (float3 center, float2 size) {
		}

		public void WireRectangle (Rect rect) {
		}

		public void SolidRectangle (Rect rect) {
		}

		public void WireGrid (float2 center, int2 cells, float2 totalSize) {
		}

		public void WireGrid (float3 center, int2 cells, float2 totalSize) {
		}

		public void WireRing (float2 center, float innerRadius, float outerRadius, float startAngle = 0f, float endAngle = 2 * math.PI) {
		}

		public void WireRing (float3 center, float innerRadius, float outerRadius, float startAngle = 0f, float endAngle = 2 * math.PI) {
		}

		public void SolidRing (float2 center, float innerRadius, float outerRadius, float startAngle = 0f, float endAngle = 2 * math.PI) {
		}

		public void SolidRing (float3 center, float innerRadius, float outerRadius, float startAngle = 0f, float endAngle = 2 * math.PI) {
		}
	}
}
#endif
